package mx.spin.mobile.dao;


import android.os.Parcel;
import android.os.Parcelable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "COUNTRIES".
 */
public class countries implements Parcelable {

    private String country_id;
    private String country_code;
    private String country;

    public countries() {
    }

    public countries(String country_id, String country_code, String country) {
        this.country_id = country_id;
        this.country_code = country_code;
        this.country = country;
    }

    protected countries(Parcel in) {
        country_id = in.readString();
        country_code = in.readString();
        country = in.readString();
    }


    public String getCountry_id() {
        return country_id;
    }

    public void setCountry_id(String country_id) {
        this.country_id = country_id;
    }

    public String getCountry_code() {
        return country_code;
    }

    public void setCountry_code(String country_code) {
        this.country_code = country_code;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public static final Creator<countries> CREATOR = new Creator<countries>() {
        @Override
        public countries createFromParcel(Parcel in) {
            return new countries(in);
        }

        @Override
        public countries[] newArray(int size) {
            return new countries[size];
        }
    };


    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(country_id);
        dest.writeString(country_code);
        dest.writeString(country);
    }
}
