package mx.spin.mobile.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "EQUIPMENT".
 */
public class Equipment {

    private Integer pool_user_id;
    private Long id;
    private Integer pooleq_id;
    private Integer pooleq_equipment_id;
    private String pooleq_qty;
    private String pooleq_hp;
    private String Equipment;

    public Equipment() {
    }

    public Equipment(Long id) {
        this.id = id;
    }

    public Equipment(Integer pool_user_id, Long id, Integer pooleq_id, Integer pooleq_equipment_id, String pooleq_qty, String pooleq_hp, String Equipment) {
        this.pool_user_id = pool_user_id;
        this.id = id;
        this.pooleq_id = pooleq_id;
        this.pooleq_equipment_id = pooleq_equipment_id;
        this.pooleq_qty = pooleq_qty;
        this.pooleq_hp = pooleq_hp;
        this.Equipment = Equipment;
    }

    public Integer getPool_user_id() {
        return pool_user_id;
    }

    public void setPool_user_id(Integer pool_user_id) {
        this.pool_user_id = pool_user_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getPooleq_id() {
        return pooleq_id;
    }

    public void setPooleq_id(Integer pooleq_id) {
        this.pooleq_id = pooleq_id;
    }

    public Integer getPooleq_equipment_id() {
        return pooleq_equipment_id;
    }

    public void setPooleq_equipment_id(Integer pooleq_equipment_id) {
        this.pooleq_equipment_id = pooleq_equipment_id;
    }

    public String getPooleq_qty() {
        return pooleq_qty;
    }

    public void setPooleq_qty(String pooleq_qty) {
        this.pooleq_qty = pooleq_qty;
    }

    public String getPooleq_hp() {
        return pooleq_hp;
    }

    public void setPooleq_hp(String pooleq_hp) {
        this.pooleq_hp = pooleq_hp;
    }

    public String getEquipment() {
        return Equipment;
    }

    public void setEquipment(String Equipment) {
        this.Equipment = Equipment;
    }

}
