package mx.spin.mobile.dao;

import android.os.Parcel;
import android.os.Parcelable;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "STATES".
 */
public class states implements Parcelable {

    private String state_id;
    private String state;

    public states() {
    }

    public states(String state_id, String state) {
        this.state_id = state_id;
        this.state = state;
    }

    protected states(Parcel in) {
        state_id = in.readString();
        state = in.readString();
    }



    public String getState_id() {
        return state_id;
    }

    public void setState_id(String state_id) {
        this.state_id = state_id;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }


    public static final Creator<states> CREATOR = new Creator<states>() {
        @Override
        public states createFromParcel(Parcel in) {
            return new states(in);
        }

        @Override
        public states[] newArray(int size) {
            return new states[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(state_id);
        dest.writeString(state);
    }
}
