package mx.spin.mobile.dao;

import android.os.Parcel;
import android.os.Parcelable;
// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "USER".
 */
public class User implements Parcelable  {

    private Long id;
    private Integer id_user;
    private String name;
    private String country;
    private String state;
    private String mail;
    private String profilePicture;
    private String phone;
    private Integer total_pools;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer id_user, String name, String country, String state, String mail, String profilePicture, String phone, Integer total_pools) {
        this.id = id;
        this.id_user = id_user;
        this.name = name;
        this.country = country;
        this.state = state;
        this.mail = mail;
        this.profilePicture = profilePicture;
        this.phone = phone;
        this.total_pools = total_pools;
    }

    protected User(Parcel in) {
        this.name = in.readString();
        this.country = in.readString();
        this.state = in.readString();
        this.mail = in.readString();
        this.profilePicture = in.readString();
        this.phone = in.readString();
    }



    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getId_user() {
        return id_user;
    }

    public void setId_user(Integer id_user) {
        this.id_user = id_user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getMail() {
        return mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getProfilePicture() {
        return profilePicture;
    }

    public void setProfilePicture(String profilePicture) {
        this.profilePicture = profilePicture;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Integer getTotal_pools() {
        return total_pools;
    }

    public void setTotal_pools(Integer total_pools) {
        this.total_pools = total_pools;
    }

    public static final Creator<User> CREATOR = new Creator<User>() {
        @Override
        public User createFromParcel(Parcel in) {
            return new User(in);
        }

        @Override
        public User[] newArray(int size) {
            return new User[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.name);
        dest.writeString(this.country);
        dest.writeString(this.state);
        dest.writeString(this.mail);
        dest.writeString(this.profilePicture);
        dest.writeString(this.phone);
    }
}
